### ISSUE TITLE
Filmavondje

### ISSUE THREAD

**Issue by DeAardbolMan** [KonnectDev/konnect#42]
Elke avond filmavondje om weer te ontspannen van de harde werkdagen. 

Vertel welke film je hebt gekeken, wat je er van vond en wat je er bij hebt gegeten.

**Comment by DeAardbolMan** [comment]
Vanavond sla ik een avondje over, want ik heb wel betere dingen te doen in mijn leven. En jullie @jakehutten @koningstein @SjoerdvDorp @Timo123950 ?

**Comment by jakehutten** [comment]
![storyboard.PNG](https://images.zenhubusercontent.com/5eb91e3e2f52cc228adee4db/8181a367-c2a9-44e8-b083-6acc22eab3a1)
